spring:
  zipkin:
    baseUrl: http://localhost:9411/  
    enabled: true    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  healthcheck:
      enabled: true
  lease:
      duration: 5
      
      
---
spring:
  profiles: docker
  zipkin:
    enabled: true    
    baseUrl: http://zipkinserver:9411/            

eureka:
  profiles: docker
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/    